apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring-boot
  name: spring-boot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot
  template:
    metadata:
      labels:
        app: spring-boot
    spec:
      containers:
      - image: selmi1999/spring-boot-hello-world:latest
        name: spring-boot-hello-world
        ports:
        - containerPort: 8080
